// Book Database Store
const INITIAL_BOOKS = [
  // --- ROMANCE CATEGORY (15 Books) ---
  {
    id: "great-gatsby",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Romance",
    rating: 5,
    price: 15.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    description: "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan. A portrait of the Jazz Age in all its decadence and excess.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 1925,
    stock: 0, // OUT OF STOCK 1
    reviews: []
  },
  {
    id: "pride-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Romance",
    rating: 5,
    price: 12.50,
    cover: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    description: "The classic romantic comedy of manners, following the turbulent relationship between Elizabeth Bennet and the wealthy, proud Fitzwilliam Darcy.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 1813,
    stock: 8,
    reviews: []
  },
  {
    id: "the-alchemist",
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Romance",
    rating: 5,
    price: 14.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    description: "A magical fable about Santiago, an Andalusian shepherd boy, who yearns to travel in search of a worldly treasure and finds a treasure within himself.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 1988,
    stock: 5,
    reviews: []
  },
  {
    id: "normal-people",
    title: "Normal People",
    author: "Sally Rooney",
    category: "Romance",
    rating: 4,
    price: 16.99,
    cover: "https://covers.openlibrary.org/b/isbn/9781984822178-L.jpg",
    description: "An intimate story of Marianne and Connell, two young people who navigate the complexities of class, mental health, and love as they grow from school to university.",
    isTrending: true,
    isHotPick: false,
    publishedYear: 2018,
    stock: 0, // OUT OF STOCK 2
    reviews: []
  },
  {
    id: "tomorrow-tomorrow-tomorrow",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    category: "Romance",
    rating: 5,
    price: 18.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780593321201-L.jpg",
    description: "Spanning thirty years, this is a modern story of Sam and Sadie, two friends who become superstar video game developers, exploring love, loss, and creative partnership.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2022,
    stock: 7,
    reviews: []
  },
  {
    id: "the-girl-who-fell-beneath-the-sea",
    title: "The Girl Who Fell Beneath the Sea",
    author: "Axie Oh",
    category: "Romance",
    rating: 5,
    price: 18.00,
    cover: "https://covers.openlibrary.org/b/isbn/9781250780867-L.jpg",
    description: "To save her brother's beloved from being sacrificed to the Sea God, Mina throws herself into the water, sweeping away into the Spirit Realm to wake the god and break a deadly curse.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2022,
    stock: 6,
    reviews: []
  },
  {
    id: "court-thorns-roses",
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    category: "Romance",
    rating: 5,
    price: 18.00,
    cover: "https://covers.openlibrary.org/b/isbn/9781619635180-L.jpg",
    description: "Feyre is dragged to a treacherous magical land after killing a faerie wolf. There, she discovers a passionate and dangerous romance with a high lord of the Fae.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2015,
    stock: 9,
    reviews: []
  },
  {
    id: "fourth-wing",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    category: "Romance",
    rating: 5,
    price: 20.00,
    cover: "https://covers.openlibrary.org/b/isbn/9781649374042-L.jpg",
    description: "Enter the brutal world of a military college for dragon riders, where the only rule is: graduate or die. Violet must survive training and find love amid chaos.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2023,
    stock: 6,
    reviews: []
  },
  {
    id: "iron-flame-catalog",
    title: "Iron Flame",
    author: "Rebecca Yarros",
    category: "Romance",
    rating: 5,
    price: 21.00,
    cover: "https://covers.openlibrary.org/b/isbn/9781649374172-L.jpg",
    description: "She survived her first year at Basgiath War College—but the real test begins now. Violet is pushed beyond her limits as she tries to protect the ones she loves.",
    isTrending: true,
    isHotPick: false,
    publishedYear: 2023,
    stock: 3,
    reviews: []
  },
  {
    id: "song-of-achilles",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    category: "Romance",
    rating: 5,
    price: 15.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780062060624-L.jpg",
    description: "A thrilling, beautifully written retelling of the Iliad, following the deep, romantic bond between the gentle Patroclus and the heroic Achilles from boyhood to the Trojan War.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2011,
    stock: 8,
    reviews: []
  },
  {
    id: "circe",
    title: "Circe",
    author: "Madeline Miller",
    category: "Romance",
    rating: 5,
    price: 16.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg",
    description: "In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child – not powerful like her father, nor vicious like her mother.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2018,
    stock: 2,
    reviews: []
  },
  {
    id: "ocean-end-of-lane",
    title: "The Ocean at the End of the Lane",
    author: "Neil Gaiman",
    category: "Romance",
    rating: 4,
    price: 14.50,
    cover: "https://covers.openlibrary.org/b/isbn/9780062255655-L.jpg",
    description: "A dark, magical fable about memory, childhood, and the terrifying forces of the supernatural, revolving around a man recalling the magical girl next door.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2013,
    stock: 10,
    reviews: []
  },
  {
    id: "harry-potter-sorcerer",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    category: "Romance",
    rating: 5,
    price: 12.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
    description: "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified he will discover he's a wizard.",
    isTrending: true,
    isHotPick: false,
    publishedYear: 1997,
    stock: 7,
    reviews: []
  },
  {
    id: "lightning-thief",
    title: "The Lightning Thief",
    author: "Rick Riordan",
    category: "Romance",
    rating: 5,
    price: 9.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg",
    description: "Percy Jackson is a good kid, but he can't seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2005,
    stock: 5,
    reviews: []
  },
  {
    id: "where-crawdads-sing",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    category: "Romance",
    rating: 5,
    price: 18.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg",
    description: "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2018,
    stock: 6,
    reviews: []
  },

  // --- THRILLER CATEGORY (20 Books) ---
  {
    id: "1984",
    title: "1984",
    author: "George Orwell",
    category: "Thriller",
    rating: 5,
    price: 14.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    description: "Winston Smith toes the Party line, rewriting history to satisfy the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 1949,
    stock: 9,
    reviews: []
  },
  {
    id: "mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Thriller",
    rating: 5,
    price: 15.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780446310789-L.jpg",
    description: "Compassionate, dramatic, and deeply moving, this novel takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 1960,
    stock: 8,
    reviews: []
  },
  {
    id: "the-hobbit",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Thriller",
    rating: 5,
    price: 16.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780345339683-L.jpg",
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 1937,
    stock: 3,
    reviews: []
  },
  {
    id: "hunger-games",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    category: "Thriller",
    rating: 5,
    price: 14.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780439023528-L.jpg",
    description: "In the ruins of a place once known as North America lies the nation of Panem, an ostentatious Capitol surrounded by twelve outlying Districts. Katniss Everdeen volunteers to take her sister's place in the games.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2008,
    stock: 7,
    reviews: []
  },
  {
    id: "catcher-rye",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Thriller",
    rating: 4,
    price: 13.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
    description: "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield, describing his reflections on phoniness.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 1951,
    stock: 5,
    reviews: []
  },
  {
    id: "fahrenheit-451",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    category: "Thriller",
    rating: 5,
    price: 14.99,
    cover: "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
    description: "Guy Montag is a fireman. In his world, where television rules and literature is on the brink of extinction, firemen start fires rather than put them out. His job is to destroy the most illegal of commodities.",
    isTrending: true,
    isHotPick: false,
    publishedYear: 1953,
    stock: 6,
    reviews: []
  },
  {
    id: "animal-farm",
    title: "Animal Farm",
    author: "George Orwell",
    category: "Thriller",
    rating: 5,
    price: 11.50,
    cover: "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg",
    description: "A satirical tale of a group of farm animals who rebel against their human farmer, hoping to create a society where the animals can be equal, free, and happy.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 1945,
    stock: 10,
    reviews: []
  },
  {
    id: "lord-flies",
    title: "Lord of the Flies",
    author: "William Golding",
    category: "Thriller",
    rating: 4,
    price: 12.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780399501487-L.jpg",
    description: "At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 1954,
    stock: 4,
    reviews: []
  },
  {
    id: "book-thief",
    title: "The Book Thief",
    author: "Markus Zusak",
    category: "Thriller",
    rating: 5,
    price: 16.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780375831003-L.jpg",
    description: "Set in Germany during the public horrors of WWII, Liesel Meminger is a foster girl living outside of Munich, who scratches out a meager existence for herself by stealing when she encounters books.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2005,
    stock: 8,
    reviews: []
  },
  {
    id: "da-vinci-code",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    category: "Thriller",
    rating: 4,
    price: 15.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    description: "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2003,
    stock: 5,
    reviews: []
  },
  {
    id: "midnight-library",
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Thriller",
    rating: 5,
    price: 16.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    description: "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2020,
    stock: 7,
    reviews: []
  },
  {
    id: "dune",
    title: "Dune",
    author: "Frank Herbert",
    category: "Thriller",
    rating: 5,
    price: 19.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    description: "Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the spice melange.",
    isTrending: true,
    isHotPick: false,
    publishedYear: 1965,
    stock: 3,
    reviews: []
  },
  {
    id: "the-silent-patient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    category: "Thriller",
    rating: 5,
    price: 16.99,
    cover: "https://covers.openlibrary.org/b/isbn/9781250301703-L.jpg",
    description: "Alicia Berenson's life is seemingly perfect. One evening, she shoots her husband five times in the face, and then never speaks another word, turning into a silent enigma.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2019,
    stock: 0, // OUT OF STOCK 3
    reviews: []
  },
  {
    id: "verity",
    title: "Verity",
    author: "Colleen Hoover",
    category: "Thriller",
    rating: 5,
    price: 15.99,
    cover: "https://covers.openlibrary.org/b/isbn/9781538724736-L.jpg",
    description: "Lowen Ashleigh accepts a job offer to complete the remaining books of bestselling author Verity Crawford, discovering a terrifying unfinished manuscript in the process.",
    isTrending: true,
    isHotPick: false,
    publishedYear: 2018,
    stock: 2,
    reviews: []
  },
  {
    id: "lessons-chemistry",
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    category: "Thriller",
    rating: 5,
    price: 19.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780385547345-L.jpg",
    description: "Chemist Elizabeth Zott is not your average woman. But it’s the early 1960s and her all-male team at Hastings Research Institute takes a very unscientific view of equality.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2022,
    stock: 9,
    reviews: []
  },
  {
    id: "yellowface",
    title: "Yellowface",
    author: "R.F. Kuang",
    category: "Thriller",
    rating: 5,
    price: 18.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780063250833-L.jpg",
    description: "When Athena Liu dies in a freak accident, June Hayward steals her unfinished manuscript and publishes it as her own, leading to a dark satire on modern publishing.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2023,
    stock: 0, // OUT OF STOCK 4
    reviews: []
  },
  {
    id: "all-light-cannot-see",
    title: "All the Light We Cannot See",
    author: "Anthony Doerr",
    category: "Thriller",
    rating: 5,
    price: 19.99,
    cover: "https://covers.openlibrary.org/b/isbn/9781476746586-L.jpg",
    description: "A beautiful, stunningly ambitious novel about a blind French girl and a German boy whose paths collide in occupied France as both try to survive the devastation of World War II.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2014,
    stock: 4,
    reviews: []
  },
  {
    id: "goldfinch",
    title: "The Goldfinch",
    author: "Donna Tartt",
    category: "Thriller",
    rating: 4,
    price: 20.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780316055437-L.jpg",
    description: "Theo Decker, a thirteen-year-old New Yorker, miraculously survives an accident that tears his life apart. His journey takes him from mansions to art underworlds.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2013,
    stock: 3,
    reviews: []
  },
  {
    id: "project-hail-mary",
    title: "Project Hail Mary",
    author: "Andy Weir",
    category: "Thriller",
    rating: 5,
    price: 18.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission to save humanity. If he fails, humanity and the earth itself will perish. But he doesn't remember that.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2021,
    stock: 6,
    reviews: []
  },
  {
    id: "the-martian",
    title: "The Martian",
    author: "Andy Weir",
    category: "Thriller",
    rating: 5,
    price: 15.00,
    cover: "https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg",
    description: "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there after an intense dust storm.",
    isTrending: false,
    isHotPick: false,
    publishedYear: 2011,
    stock: 8,
    reviews: []
  },

  // --- PRE-ORDER TITLES (NOT IN BROWSE CATALOG, ONLY IN PRE-ORDERS HUB) ---
  {
    id: "the-daisy-chain",
    title: "The Daisy Chain",
    author: "Laurie Gilmore",
    category: "New Arrivals",
    rating: 5,
    price: 14.99,
    cover: "assets/the_daisy_chain.png",
    description: "A cozy romance centered around a charming small-town flower shop. Fall in love with the quirky characters and heartwarming relationships in this new arrival.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "Sophia R.", rating: 5, comment: "The ultimate cozy read. Felt like a warm hug!" },
      { reviewer: "Ben S.", rating: 4, comment: "Lovely town setting and very charming characters." }
    ]
  },
  {
    id: "the-reappearance-of-rachel-price",
    title: "The Reappearance of Rachel Price",
    author: "Holly Jackson",
    category: "New Arrivals",
    rating: 5,
    price: 19.99,
    cover: "https://covers.openlibrary.org/b/id/14605870-L.jpg",
    description: "Rachel Price vanished sixteen years ago. Her young daughter, Bel, was the only witness. But when Rachel suddenly reappears with a shocking story, Bel's world is turned upside down.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "Hannah V.", rating: 5, comment: "A thrilling mystery from start to finish. Holly Jackson is a genius!" },
      { reviewer: "Lucas N.", rating: 4, comment: "Full of twists and turns. Keeps you guessing till the final page." }
    ]
  },
  {
    id: "iron-flame",
    title: "Iron Flame",
    author: "Rebecca Yarros",
    category: "New Arrivals",
    rating: 5,
    price: 21.00,
    cover: "https://covers.openlibrary.org/b/isbn/9781649374172-L.jpg",
    description: "She survived her first year at Basgiath War College—but the real test begins now. Violet Sorrengail has always been expected to die during her first year. A new sequel in the series.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "Arthur K.", rating: 5, comment: "Even better than Fourth Wing! The dragon action is epic." },
      { reviewer: "Sienna J.", rating: 5, comment: "Stunning fantasy world-building. A perfect sequel." }
    ]
  },
  {
    id: "house-of-flame-and-shadow",
    title: "House of Flame and Shadow",
    author: "Sarah J. Maas",
    category: "New Arrivals",
    rating: 5,
    price: 22.00,
    cover: "https://covers.openlibrary.org/b/isbn/9781635574104-L.jpg",
    description: "The stunning third installment in the Crescent City series. Bryce Quinlan is stranded in a strange new world, desperate to find her way back to Midgard to save her world.",
    isTrending: false,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "Morgan D.", rating: 5, comment: "Mind-blowing crossover elements. Sarah J. Maas does it again!" },
      { reviewer: "Kate R.", rating: 4, comment: "An epic conclusion to the trilogy, packed with emotional stakes." }
    ]
  },
  {
    id: "alchemised",
    title: "Alchemised",
    author: "SenLinYu",
    category: "New Arrivals",
    rating: 5,
    price: 24.99,
    cover: "https://covers.openlibrary.org/b/isbn/9780593972700-L.jpg",
    description: "A stunning dark fantasy novel from global sensation SenLinYu. Set in a war-torn magical world, this deluxe edition tells the story of survival, power, and a forbidden alliance.",
    isTrending: true,
    isHotPick: true,
    publishedYear: 2025,
    reviews: [
      { reviewer: "Tessa G.", rating: 5, comment: "Breathtaking dark fantasy. Absolutely gorgeous storytelling!" },
      { reviewer: "Jacob P.", rating: 5, comment: "I've been waiting for this print publication. A true masterpiece." }
    ]
  },
  {
    id: "the-book-of-grief",
    title: "សៀវភៅលាក់ទុក្ខ - The Book of Grief",
    author: "វាយោ (Vayo)",
    category: "New Arrivals",
    rating: 5,
    price: 15.00,
    cover: "assets/the_book_of_grief.jpg",
    description: `“ពាក្យពេចន៍ដែលមិនបាននិយាយ នឹងក្លាយជាសំណេរដែលបានសរសេរទុក”\n\nទុក្ខសោកខ្លះ ចូលមកដោយមិនបង្ហាញនាមអ្វីឡើយ។ វាចូលមកជិតយើងយ៉ាងស្ងៀមស្ងាត់... នៅក្នុងចិត្ត... នៅក្នុងរូបកាយ... ក្នុងស្រមោលនៃការចងចាំ និងក្នុងចន្លោះរវាងអ្វីដែលបាននិយាយចេញមក និងអ្វីដែលត្រូវបានលាក់ទុក។ «សៀវភៅលាក់ទុក្ខ» បង្ហាញពីដំណើរនៃការផ្លាស់ប្ដូរ ការនឹកនាដ៏ស្ងប់ស្ងាត់ ក្ដីសង្ឃឹម និងការធ្វើដំណើរឆ្លងកាត់ពេលវេលានៃជីវិតរបស់មនុស្សម្នាក់ និងបុគ្គលម្នាក់ទៀតដែលយើងមិនអាចបកស្រាយបាន។`,
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "ម៉ានី", rating: 5, comment: "រង់ចាំអានប្រលោមលោកថ្មីនេះណាស់! គ្រាន់តែឃើញក្របសៀវភៅក៏ទាក់ទាញបាត់ទៅហើយ។" },
      { reviewer: "សុជាតា", rating: 5, comment: "ក្របសៀវភៅស្អាតខ្លាំងណាស់ ចូលចិត្តស្នាដៃរបស់អ្នកនិពន្ធវាយោ។" }
    ]
  },
  {
    id: "kingdom-of-suriya-part-1",
    title: "អាណាចក្រសុរិយ៖ ភាគទី១ - Kingdom of Suriya: Part 1",
    author: "សំណេរ (Somnae)",
    category: "New Arrivals",
    rating: 5,
    price: 14.00,
    cover: "assets/kingdom_of_suriya_part_1.jpg",
    description: `✨𝐎𝐏𝐄𝐍 𝐅𝐎𝐑 𝐏𝐑𝐄-𝐎𝐑𝐃𝐄𝐑✨\n\n•• 𝐌𝐄𝐑𝐀 𝐄𝐃𝐈𝐓𝐈𝐎𝐍\n(Pre-Order ត្រឹមតែ៖ ៥៦,០០០៛ | $14.00) ✔️\n\nទទួលបាន៖\n- សៀវភៅ «អាណាចក្រសុរិយ៖ ភាគទី១» ប្រភេទក្របរឹង Hard Cover ចំនួន 1ក្បាល\n- ហត្ថលេខា អ្នកនិពន្ធ និង វិចិត្រករ\n- ស្នៀតសៀវភៅ ចំនួន៤\n- ស្នៀតសៀវភៅតួអង្គ Diecut ចំនួន៣\n- Postcard តួអង្គ ខ្នាត A5 ចំនួន៣\n- Postcard ពិសេស ខ្នាត A5 ចំនួន១\n- ផ្ទាំងផែនទីនៃអាណាចក្រសុរិយ ខ្នាត A3 ចំនួន១\n- ផ្ទាំងរូបភាពនៃរាជធានីសុរិយ ខ្នាត A3 ចំនួន១\n- ប្រអប់ការពារសៀវភៅ + ការវេចខ្ចប់ពិសេស\n\n*បិទកក់ត្រឹមថ្ងៃទី០៥ ខែមីនា ឆ្នាំ២០២៦*`,
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "ដារ៉ា", rating: 5, comment: "សៀវភៅ Mera Edition នេះរៀបចំឡើងមកប្រណីតមែនទែន! ប្រអប់និងកញ្ចប់ពិសេសគឺស្អាតរកគាស់មិនបាន។" },
      { reviewer: "ចាន់ថា", rating: 5, comment: "គំនូរនិងសាច់រឿងលំដាប់ខ្ពស់ខ្លាំងណាស់ គាំទ្រស្នាដៃខ្មែរ!" }
    ]
  },
  {
    id: "find-me-reminder",
    title: "ចំណងដានជតា - Find me, reminder",
    author: "នីម៉ូសា (Nimosa)",
    category: "New Arrivals",
    rating: 5,
    price: 15.50,
    cover: "assets/find_me_reminder.jpg",
    description: `“យើងមិនមែនទេវតា យើងគ្រាន់តែជាកែសម្រួលអក្ខរាវិរុទ្ធតែប៉ុណ្ណោះ”\n\nនៅពេលសាកសពនិស្សិតម្នាក់ត្រូវបានគេរកឃើញនៅក្បែរមាត់ទ្វារបន្ទប់ស្នាក់នៅ បរិវេណសាកលវិទ្យាល័យទាំងមូលក៏ដួលរលំទៅក្នុងភាពភ័យខ្លាច។ មានតែ វីរ៉ា ម្នាក់គត់ដែលរក្សាភាពស្ងប់ស្ងាត់ហាក់គ្មានរឿងអ្វីកើតឡើង។ នៅពីក្រោយរបាំងមុខនៃភាពព្រងើយកន្តើយ នាងនឹងប្រមាញ់ការពិត បំពេញភារកិច្ចក្នុងការបោសសម្អាត រៀបចំសណ្ដាប់ធ្នាប់ និងបញ្ចប់រាល់ភាពចលាចលទាំងឡាយដោយដៃរបស់នាងផ្ទាល់。\n\nសៀវភៅប្រលោមលោកបែបអាថ៌កំបាំង អភិនីហារ - SchoolVibe\nបោះពុម្ពផ្សាយដោយ៖ សំណេរ\nអ្នកសរសេរ៖ នីម៉ូសា\nត្រួតពិនិត្យ និងសម្រួល៖ តាំង ហ៊ុយសេង`,
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "វីរៈ", rating: 5, comment: "សាច់រឿងបែបស៊ើបអង្កេតអាថ៌កំបាំងក្នុងសាលា គួរឱ្យចាប់អារម្មណ៍ខ្លាំងណាស់!" },
      { reviewer: "លីណា", rating: 4, comment: "ចូលចិត្តភាពរំភើបញាប់ញ័រនិងការស៊ើបអង្កេតក្នុងរឿងនេះ។" }
    ]
  },
  {
    id: "the-heartbroken-man",
    title: "បុរសខកស្នេហ៍ - The Heartbroken Man",
    author: "សំណេរ (Somnae)",
    category: "New Arrivals",
    rating: 5,
    price: 16.00,
    cover: "assets/the_heartbroken_man.jpg",
    description: `🏆 OST. នៃសៀវភៅ «បុរសខកស្នេហ៍» - បទចម្រៀង «តួរងល្អឥតខ្ចោះ»\n\nការប្រកួតច្រៀងចម្រៀង Song Cover Contest៖\n🏆ជ័យលាភីលេខ១៖ ទទួលបានឈុត Gentleman Edition + សៀវភៅ៣០ក្បាល + Original CD\n🏆ជ័យលាភីលេខ២៖ ទទួលបានឈុត Gentleman Edition + សៀវភៅ១៥ក្បាល + Original CD\n🏆ជ័យលាភីលេខ៣៖ ទទួលបានឈុត Gentleman Edition + សៀវភៅ១០ក្បាល + Original CD\n\nលក្ខខណ្ឌក្នុងការចូលរួម៖\n- ត្រូវ Cover តាមបទចម្រៀង «តួរងល្អឥតខ្ចោះ»\n- រយៈពេលនៃវីដេអូ ចាប់ពី២នាទីឡេីងទៅ\n- Link ទៅកាន់បទចម្រៀង៖ https://youtu.be/KQpqOiwEYss?si=C0LmXnXCD4EGkxoS\n- ភ្លេងសុទ្ធ៖ https://youtu.be/BluACzrF7Xk?si=Ahbcp9K4mg6FwSSL\n- ត្រូវបង្ហោះវីដេអូចូលរួមនៅលេី Facebook ឬ TikTok ឬ YouTube\n- ភ្ជាប់ជាមួយ hashtag #SomnaeSongCoverContest #តួរងល្អឥតខ្ចោះ\n- ផុតកំណត់ត្រឹមថ្ងៃទី១៤ ខែកុម្ភៈ ឆ្នាំ២០២៦`,
    isTrending: true,
    isHotPick: true,
    publishedYear: 2026,
    reviews: [
      { reviewer: "សុខា", rating: 5, comment: "បទចម្រៀងពិរោះខ្លាំងណាស់ ស្តាប់ហើយចង់អានសៀវភៅតែម្តង!" },
      { reviewer: "ភារម្យ", rating: 5, comment: "ឈុត Gentleman Edition ពិតជាទាក់ទាញខ្លាំងណាស់ ចង់បាន CD ណាស់!" }
    ]
  }
];

// Helper to get all categories in browse (excluding New Arrivals which is pre-order only)
const CATEGORIES = ["All Books", "Romance", "Thriller"];

// Export data to global scope so it's easily accessible in other scripts
window.BookStore = {
  INITIAL_BOOKS,
  CATEGORIES
};
